# fly.toml app configuration file generated for spiderfoot on 2025-04-25T18:19:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "spiderfoot"
primary_region = "lax"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[services]]
  internal_port = 5001
  protocol = "tcp"
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 81
    handlers = ["http"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
